routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login' ,' Auth\LoginController@showLoginForm')->name('login');
Route::post('/loggingin' , 'Auth\LoginController@attemptLogin')->name('loggingin');
route::post('/logout' , 'Auth\LoginController@logout')->name('logout');

// Extra Routes for web application to export Excel and PDF for meal schedule tea schedule and
// Inventory listing

Route::get('/meal/export', 'Admin\Employee\ExtraController@exportMeal')->name('export.meal');
Route::get('/export/meal' , 'Admin\Employee\ExtraController@exportExcel')->name('export.excel');
Route::get('/export/tea' , 'Admin\Employee\ExtraController@exportTea')->name('tea.pdf');
Route::get('tea/export', 'Admin\Employee\ExtraController@ExportTeaExcel')->name('export.tea.excel');
Route::get('date/{start}/{end}/fetch' , 'Admin\Employee\ExtraController@dateRanger');
Route::get('date/{start}/{end}/fetch/tea' , 'Admin\Employee\ExtraController@dateRangerTea');
Route::get('/export/inventory' , 'Admin\Employee\ExtraController@exportInventoryPDF')->name('inventory.pdf');
Route::get('/inventory/export' , 'Admin\Employee\ExtraController@exportInventoryExcel')->name('inventory.excel');
Auth::routes();

Route::middleware('auth')->group(function () {
Route::get('/', function () {
    return view('Admin.Dashboard');
})->name('admin.dashboard');

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where Admin Panel routes are registered. Navigation and operation
| against admin role is performed by these routes.
|
*/
Route::resource('employee', 'Admin\Employee\EmployeeController');
Route::resource('meal', 'Admin\Meals\MealController');
Route::resource('product', 'Admin\Products\ProductController');
Route::resource('productcat', 'Admin\Products\ProductcategoryController')->except(['create']);
Route::resource('inventory', 'Admin\Inventory\InventoryController');
Route::get('dish/view', ['as' => 'dish.index', 'uses' => 'Admin\Dish\DishController@index']);
Route::resource('tea', 'Admin\Meals\TeaController');
Route::resource('dish', 'Admin\Dish\DishController', ['names' => [
    'index' => 'dish.view'
]])->except([
    'index'
]);

});


/*
|--------------------------------------------------------------------------
| Cook Routes
|--------------------------------------------------------------------------
|
| Here is where Cook Panel routes are registered. Navigation and operation
| against cook role is performed by these routes.
|
*/





/*
|--------------------------------------------------------------------------
| System Handler Routes
|--------------------------------------------------------------------------
|
| Here is where Handler Panel routes are registered. Navigation and operation
| against handler role is performed by these routes.
|
*/

app/Inventory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    protected $fillable = [
        'prd_id', 'quantity', 'date'
    ];
}

app/Http/Controllers/Admin/Inventory/InventoryController.php
<?php

namespace App\Http\Controllers\Admin\Inventory;

use Illuminate\Http\Request;
use App\Http\Requests\Admin\UpdateInventoryRequest;
use App\Http\Controllers\Controller;
use App\Product;
use App\Inventory;
use DB;

class InventoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Inventory::join('products', 'products.id', 'inventories.prd_id')->select(
            DB::raw('inventories.id as id'),
            DB::raw('products.prd_name as products'),
            DB::raw('products.prd_ctgry as category'),
            DB::raw('inventories.quantity as quantity'),
            DB::raw('inventories.date as date')
        )->paginate(15);

        return view('Admin.Inventory.List_inventory')->with(compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        try {
            $product = Product::where('id' , $data['prd_id'])->pluck('prd_qty')->toArray();
            if($data['quantity'] < $product[0]){
                $updated_product_quantity = $product[0] - $data['quantity'];
            Product::where('id' , $data['prd_id'])->update([
                        'prd_qty' => $updated_product_quantity
            ]);
            Inventory::create($data);
            session()->flash('alert-success', 'Product has been added to the inventory');
            return redirect()->back();
            }
            else{
                session()->flash('alert-danger' , 'Entered Quantity in greater than available quantity');
                return redirect()->back();
            }
            // Inventory::create($data);
            // session()->flash('alert-success', 'Product has been added to the inventory');
            // return redirect()->route('inventory.index');

        } catch (\Throwable $th) {

            session()->flash('alert-danger' , $th->getMessage());
            return redirect()->back();

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Product::findOrfail($id);
        return view('Admin.Inventory.Transfer_products')->with(compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Inventory::findOrfail($id);
        return view('Admin.Inventory.Edit_Inventory')->with(compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateInventoryRequest $request, $id)
    {
        $data = $request->all();
        try{

            Inventory::where('id' , $id)->update([
                'quantity' => $data['quantity'],
                'date' => $data['date']
            ]);
            session()->flash('alert-success' , 'inventory updated successfully');
            return redirect()->route('inventory.index');

        }catch(\Throwable $th){

            session()->flash('alert-danger' , 'cannot update inventory, please try again');
            return redirect()->back();

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{

            Inventory::where('id', $id)->delete();
            session()->flash('alert-success' , 'Product has been deleted successfylly');
            return redirect()->back();

        }catch(\Throwable $th){

            session()->flash('alert-danger' , 'Product cannot be deleted, Please try again');
            return redirect()->back();

        }
    }
}

resources/views/Admin/Inventory/Add_product.blade.php
@extends('index')
@section('content')

<div class="row">
    <div class="col-sm-12" style="background-color:white">
        <form action="" class="form" method="POST" enctype="multipart/form-data">
        @CSRF
        <div class="row">
            <div class="form-group col-md-6">
                <label for="prod_name">Product Name</label>
                <input type="text" class="form-control" name="prod_name" placeholder="Enter Product Name">
            </div>
        </div>
        <div class="row" style="margin-top:2%">
            <div class="col-md-6">
                <button class="btn btn-primary" type="submit" name="submit" value="submit">Submit</button>
            </div>
        </div>
        </form>
    </div>
    </div>

@endsection

resources/views/Admin/Inventory/Edit_Inventory.blade.php
@extends('index')
@section('content')

<div class="col-sm-12" style="background-color:white">
        <form action="{{ route('inventory.update', $data->id) }}" class="form" method="POST" enctype="multipart/form-data">
            @CSRF
            @method('PATCH')
            <div class="row">
            <div class="form-group col-md-6">
                    <label for="">Product Quantity</label>
            <input type="number" name="quantity" class="form-control{{ $errors->has('quantity') ? 'is-invalid' : '' }}" value="{{ $data->quantity }}">
            @if ($errors->has('quantity'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('quantity') }}</strong>
                </span>
            @endif
            </div>
            <div class="col-md-6">
                    <label for="">Date</label>
            <input type="date" class="form-control{{ $errors->has('date') ? 'is-invalid' : '' }}" name="date" value="{{ $data->date }}">
            @if ($errors->has('date'))
                <strong>{{ $errors->first('date') }}</strong>
            @endif
            </div>
            </div>
            <div class="row" style="margin-top:2%">
                <div class="col-md-12">
                    <button class="btn btn-success pull-right" type="submit" name="submit" value="submit">Submit</button>
                </div>
            </div>
            </form>
        </div>
        </div>

@stop
@section('section')
<h1>Edit Inventory</h1>
<hr>
<ol class="breadcrumb">
        <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Edit Inventory</li>
        </ol>
@endsection

resources/views/Admin/Inventory/List_inventory.blade.php
@extends('index')
@section('content')
<div class="row">
    <div class="col-xs-6 ">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search by Name" onkeyup="search_name()" id="s_name">
            <div class="input-group-btn search-panel">
                <button class="btn btn-success" style="border:none">
                    <span id="search_concept" style="color:white">Search By Name</span>
                </button>
            </div>
            <span class="input-group-btn">
                <i class="far fa-search"></i>
            </span>
        </div>
    </div>
        <div class="col-xs-6 ">
            <div class="input-group">
                <input type="text" id="s_name" class="form-control" placeholder="search by product name" onkeyup="search_name()">
                <div class="input-group-btn search-panel">
                    <button class="btn btn-warning" style="border:none">
                        <span id="search_concept" style="color:white">Search By category</span>
                    </button>
                </div>
                <span class="input-group-btn">
                    <i class="far fa-search"></i>
                </span>
        </div>
    </div>
    </div>
    <hr>
    <div class="row" style="margin-top:4%">
        <div class="col-sm-12">
        <a href="{{ route('inventory.pdf') }}"><button class="btn btn-primary btn-xs pull-right" style="margin-left:4%">Export to PDF</button></a>
        <a href="{{ route('inventory.excel') }}"><button class="btn-success btn btn-xs pull-right">Export to Excel</button></a>
        </div>
    </div>
    <hr>
    <div class="row" style="background-color:white; margin-top:4%">
        <table class="table" id="myTable">
            <thead>
                <th>No.</th>
                <th>Product Name</th>
                <th>Product Category</th>
                <th>Quantity</th>
                <th>Date Added</th>
                <th>Actions</th>
            </thead>
            <tbody>
                @foreach($data as $info)
                <tr>
                    <td class="counterCell"></td>
                <td>{{ $info->products }}</td>
                <td>{{ $info->category }}</td>
                <td>{{ $info->quantity }}</td>
                <td>{{ $info->date }}</td>
                <td><form action="{{ route('inventory.destroy',$info->id) }}" method="POST"  data-confirm="Are you sure you want to delete this row?">
                @CSRF @method('DELETE')<button type="submit" class="btn-danger btn btn-xs pull-left">Delete</button>
                </form><a href="{{ route('inventory.edit',$info->id) }}"><button class="btn btn-primary btn-xs pull-left">Edit</button></a></td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {{ $data->links() }}
    </div>
@stop
@section('footer_scripts')
<script>
    function search_name() {
        var input, filter, table, tr, td, i;
        input = document.getElementById("s_name");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[1];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

    function search_cat() {
        var input, filter, table, tr, td, i;
        input = document.getElementById("c_name");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[2];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

    $(document).on('submit', 'form[data-confirm]', function(e){
    if(!confirm($(this).data('confirm'))){
    	e.stopImmediatePropagation();
      e.preventDefault();
		}
});
</script>
@endsection

resources/views/Admin/Inventory/Print_inventory_list.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PDF Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


<style>
        table {
                   counter-reset: tableCount;
               }

               .counterCell:before {
                   content: counter(tableCount);
                   counter-increment: tableCount;
               }
       </style>
</head>
<body>
        <table class="table" style="width:100%">
                <tr>
                    <th>No.</th>
                    <th>Product Name</th>
                    <th>Product Category</th>
                    <th>Quantity</th>
                    <th>Date Added</th>
                </tr>
                <tbody>
                    @foreach ($datas as $info)
                    <tr>
                    <td class="counterCell"></td>
                    <td>{{ $info->products }}</td>
                    <td>{{ $info->category }}</td>
                    <td>{{ $info->quantity }}</td>
                    <td>{{ $info->date }}</td>
                    </tr>
                    @endforeach
                </tbody>
                <?php  //dd($datas); ?>
        </table>

</body>

</html>

resources/views/Admin/Inventory/Transfer_products.blade.php
@extends('index')
@section('content')
<div class="row" style="background-color:white">
    <div class="col-sm-12" >
        <table class="table">
            <tbody>
                <tr>
                    <td><strong>Product Name</strong></td>
                <td>{{ $data->prd_name }}</td>
                </tr>
                <tr>
                    <td><strong>Product Category</strong></td>
                <td>{{ $data->prd_ctgry }}</td>
                </tr>
                <tr>
                    <td><strong>Product Price</strong></td>
                <td>{{ $data->prd_price }}</td>
                </tr>
                <tr>
                    <td><strong>Available Quantity</strong></td>
                    <td>
                    @if($data->prd_qty >= 10 && $data->prd_qty <= 20 )
                    <strong style="background-color:yellow; padding:2%">{{ $data->prd_qty }}</strong>
                    @elseif($data->prd_qty > 20)
                    <strong style="background-color:green; padding:2%">{{ $data->prd_qty }}</strong>
                    @elseif($data->prd_qty < 10)
                    <strong style="background-color:red; color:white; padding:2%">{{ $data->prd_qty }}</strong>
                     @endif
                    </td>
                </tr>
            </tbody>

        </table>
    </div>
    <hr><br>
    <div class="col-sm-12">
    <form action="{{ route('inventory.store') }}" class="form" method="POST" enctype="multipart/form-data" id="Add_inventory_form" data-confirm="Are you sure you want to add this quantity?">
        @CSRF
        <div class="row">
        <input type="hidden" name="prd_id" value="{{ $data->id }}" readonly>
        <div class="form-group col-md-6">
                <label for="">Product Quantity</label>
        <input type="number" name="quantity" class="form-control{{ $errors->has('quantity') ? 'is-invalid' : ''}}" id="quantity" value="{{ old('quantity') }}">
        @if ($errors->has('quantity'))
            <span class="invalid-feedback" role="alert">
                  <strong>{{ $errors->first('quantity') }}</strong>
            </span>
        @endif
        </div>
        <div class="col-md-6">
                <label for="">Date</label>
        <input type="date" class="form-control{{ $errors->has('date') ? 'is-invalid' : ''}}" name="date" id="date" value="{{ old('date') }}">
        @if ($errors->has('date'))
             <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('date') }}</strong>
            </span>
        @endif
        </div>
        </div>
        <div class="row" style="margin-top:2%">
            <div class="col-md-12">
                <button class="btn btn-success pull-right" type="submit" name="submit" value="submit">Submit</button>
            </div>
        </div>
        </form>
    </div>
    </div>

@stop
@section('section')
<h1>Transfer Product</h1>
<hr>
<ol class="breadcrumb">
        <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Transfer Product</li>
        </ol>
@stop
@section('footer_scripts')
<script>
$(document).on('submit', 'form[data-confirm]', function(e){
    if(!confirm($(this).data('confirm'))){
    	e.stopImmediatePropagation();
      e.preventDefault();
		}
});
</script>
@endsection