routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login' ,' Auth\LoginController@showLoginForm')->name('login');
Route::post('/loggingin' , 'Auth\LoginController@attemptLogin')->name('loggingin');
route::post('/logout' , 'Auth\LoginController@logout')->name('logout');

// Extra Routes for web application to export Excel and PDF for meal schedule tea schedule and
// Inventory listing

Route::get('/meal/export', 'Admin\Employee\ExtraController@exportMeal')->name('export.meal');
Route::get('/export/meal' , 'Admin\Employee\ExtraController@exportExcel')->name('export.excel');
Route::get('/export/tea' , 'Admin\Employee\ExtraController@exportTea')->name('tea.pdf');
Route::get('tea/export', 'Admin\Employee\ExtraController@ExportTeaExcel')->name('export.tea.excel');
Route::get('date/{start}/{end}/fetch' , 'Admin\Employee\ExtraController@dateRanger');
Route::get('date/{start}/{end}/fetch/tea' , 'Admin\Employee\ExtraController@dateRangerTea');
Route::get('/export/inventory' , 'Admin\Employee\ExtraController@exportInventoryPDF')->name('inventory.pdf');
Route::get('/inventory/export' , 'Admin\Employee\ExtraController@exportInventoryExcel')->name('inventory.excel');
Auth::routes();

Route::middleware('auth')->group(function () {
Route::get('/', function () {
    return view('Admin.Dashboard');
})->name('admin.dashboard');

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where Admin Panel routes are registered. Navigation and operation
| against admin role is performed by these routes.
|
*/
Route::resource('employee', 'Admin\Employee\EmployeeController');
Route::resource('meal', 'Admin\Meals\MealController');
Route::resource('product', 'Admin\Products\ProductController');
Route::resource('productcat', 'Admin\Products\ProductcategoryController')->except(['create']);
Route::resource('inventory', 'Admin\Inventory\InventoryController');
Route::get('dish/view', ['as' => 'dish.index', 'uses' => 'Admin\Dish\DishController@index']);
Route::resource('tea', 'Admin\Meals\TeaController');
Route::resource('dish', 'Admin\Dish\DishController', ['names' => [
    'index' => 'dish.view'
]])->except([
    'index'
]);

});


/*
|--------------------------------------------------------------------------
| Cook Routes
|--------------------------------------------------------------------------
|
| Here is where Cook Panel routes are registered. Navigation and operation
| against cook role is performed by these routes.
|
*/





/*
|--------------------------------------------------------------------------
| System Handler Routes
|--------------------------------------------------------------------------
|
| Here is where Handler Panel routes are registered. Navigation and operation
| against handler role is performed by these routes.
|
*/

app/Http/Controllers/Admin/Employee/EmployeeController.php
<?php

namespace App\Http\Controllers\Admin\Employee;

use Illuminate\Http\Request;
use App\Http\Requests\Admin\AddUserRequest;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\Hash;
class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = User::whereNotNull('role')->paginate(15);
        return view('Admin.Employees.List_employee')->with(compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.Employees.Add_Employee');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddUserRequest $request)
    {
        $data = $request->all();
        $user = User::where('email' , '=' , $data['email'])->first();
        if($user === null){
        try {
            $employee_id_get = date('m/d/Y h:i:s a', time());
            // hashing the time
            $employee_id_hash = md5($employee_id_get);
            // trimming the string to 6 letter ( 32-26 = 6) substring;
            $employee_id = substr($employee_id_hash, 0, -26);

            $user = new User();
            $user->fname = $data['fname'];
            $user->lname = $data['lname'];
            $user->mobile = $data['mobile'];
            $user->email = $data['email'];
            $user->password = Hash::make($data['password']);
            $user->role = $data['role'];
            $user->status = $data['status'];
            $user->emp_num = $employee_id;
            $user->save();
            session()->flash('alert-success', 'User Added Successfully');
            return redirect()->route('employee.index');

        } catch (\Throwable $th) {

            session()->flash('alert-danger' , $th->getMessage());
            return redirect()->back();
        }
    }
        else{
            session()->flash('alert-danger' , 'User Email Already Exists');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       return view('Admin.Employees.profile');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = User::findOrfail($id);
        return view('Admin.Employees.Edit_employee')->with(compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        if(isset($_POST['update_profile'])){
            // checking if request has image
            if($request->hasFile('img')) {
                $file = $request->file('img');
                $filename = $file->getClientOriginalName();
                $extension = $file->getClientOriginalExtension();
                $imgname = uniqid().$filename;
                $destinationPath = public_path('/user_img/');
                $file -> move($destinationPath , $imgname);
              }
            try {
                //if user submits form with image and password
                if(!empty($data['img']) && !empty($data['password'])){
                User::where('id', $id)->update([
                    'password' => Hash::make($data['password']),
                    'img' => $imgname,
                ]);
                session()->flash('alert-success', 'User Updated successfully');
                return redirect()->back();
                }
                //if user submits form without image
                elseif(!empty($data['password']) && empty($data['img'])){
                    User::where('id', $id)->update([
                        'password' => Hash::make($data['password'])
                    ]);
                        session()->flash('alert-success', 'Password Updated successfully');
                        return redirect()->back();

                }
                //if user submits form without password
                elseif(empty($data['password']) && !empty($data['img'])){
                    User::where('id', $id)->update([
                        'img' => $imgname,
                    ]);
                        session()->flash('alert-success', 'Profile picture Updated successfully');
                        return redirect()->back();
                }
                //if users tries to submit the form without any value
                else{
                        session()->flash('alert-warning' , 'Enter Values to Update Profile');
                        return redirect()->back();
                }

            } catch (\Throwable $th) {
                session()->falsh('alert-danger' , 'User cannot be updated, please try again');
                return redirect()->back();
            }
        }

        else{
        try {

            User::where('id', $id)->update([
                'fname' => $data['fname'],
                'lname' => $data['lname'],
                'mobile' => $data['mobile'],
                'role' => $data['role'],
                'status' => $data['status'],
                'email' => $data['email']
            ]);
                session()->flash('alert-success', 'User Updated successfully');
                return redirect()->route('employee.index');

        } catch (\Throwable $th) {
                session()->flash('alert-danger' , 'User cannot be updated, please try again');
                return redirect()->back();
        }
    }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {

            User::where('id' , $id)->delete();
            session()->flash('alert-success' , 'User has been deleted successfully');
            return redirect()->back();

        } catch (\Throwable $th) {

            session()->flash('alert-danger' , 'User cannot be deleted, please try again');
            return redirect()->back();

        }
    }
}

app/Http/Controllers/Admin/Employee/ExtraController.php
<?php

namespace App\Http\Controllers\Admin\employee;

use Illuminate\Http\Request;
use App\Meal_Schedule;
use App\Http\Controllers\Controller;
use PDF;
use DB;
use Excel;
use App\Inventory;
class ExtraController extends Controller
{
    /*
    |
    | Exporting Meal Schedule history to PDF (downloaded file)
    |
    */

    public function exportMeal(){

        $datas  = DB::table('meal__schedules')->get();
        $pdf = PDF::loadView('Admin.Meals.Print_meal_schedule', compact('datas'))->setPaper('a4','portrait');
        return $pdf->stream('meals.pdf');

    }

    /*
    |
    | Export Meal schedule History to Excel (xls format downloaded file)
    |
    */

    public function exportExcel(){
        $data = Meal_Schedule::select(
            DB::raw('date as Date'),
            DB::raw('time as Time'),
            DB::raw('dish_name as Dish'),
            DB::raw("(CASE rotti WHEN 1 THEN 'Available' ELSE 'Unavailable' END) as Rotti_Available")
        )
        ->get()
        ->toArray();

        return Excel::create('Meal_Schedule', function($excel) use ($data) {
            $excel->sheet('mySheet', function($sheet) use ($data)
            {
                $sheet->fromArray($data);
            });
        })->download('xls');
    }

    /*
    |
    | Export Tea Schedule history to PDF (download file)
    |
    */

    public function exportTea(){

        $datas  = DB::table('meal__schedules')->where('tea' , 1)->get();
        $pdf = PDF::loadView('Admin.Meals.Print_tea_schedule', compact('datas'))->setPaper('a4','portrait');
        return $pdf->stream('tea.pdf');

    }

    /*
    |
    | Export Tea Schedule history to Excel (xls format downloaded file)
    |
    */

    public function exportTeaExcel(){
        $data = Meal_Schedule::select(
            DB::raw('date as Date'),
            DB::raw('time as Time'),
            DB::raw('dish_name as Product')
        )
        ->where('tea' , 1)
        ->get()
        ->toArray();

        return Excel::create('Tea_Schedule', function($excel) use ($data) {
            $excel->sheet('mySheet', function($sheet) use ($data)
            {
                $sheet->fromArray($data);
            });
        })->download('xls');
    }

    /*
    |
    | Export Inventory listing to PDF (downloaded file)
    |
    */

    public function exportInventoryPDF(){

        $datas = DB::table('inventories')->join('products', 'products.id', 'inventories.prd_id')->select(
            DB::raw('inventories.id as id'),
            DB::raw('products.prd_name as products'),
            DB::raw('products.prd_ctgry as category'),
            DB::raw('inventories.quantity as quantity'),
            DB::raw('inventories.date as date')
        )->get();
        $pdf = PDF::loadView('Admin.Inventory.Print_inventory_list' , compact('datas'))->setPaper('a4' , 'portrait');
        return $pdf->stream('inventory.pdf');

    }

    /*
    |
    | Export Inventory Listing to Excel file (xls format downloaded file)
    |
    */

    public function exportInventoryExcel(){
        $datas = Inventory::join('products', 'products.id', 'inventories.prd_id')->select(
            DB::raw('inventories.id as Number'),
            DB::raw('products.prd_name as Products'),
            DB::raw('products.prd_ctgry as Category'),
            DB::raw('inventories.quantity as Quantity'),
            DB::raw('inventories.date as Date')
        )
        ->get()
        ->toArray();
        return Excel::create('Inventory_history', function($excel) use ($datas) {
            $excel->sheet('mySheets' , function($sheet) use ($datas){
                $sheet->fromArray($datas);
            });
        })->download('xls');
    }

    /**
     * Function to handle AJAX call from view.meal.schedule JQuery DateRangepicker
     *    @param string $start where start date is passed
     *    @param string $end where end date is passed
     *    return response objects
    */

    public function dateRanger($start, $end){
        $time_1 = strtotime($start);
        $time_2 = strtotime($end);
        $start_date_format = date('Y-d-m' , $time_1);
        $end_date_format = date('Y-d-m' , $time_2);
        // $dates = $start_date_format .'-'. $end_date_format;
        $data = Meal_Schedule::select(
            DB::raw('date as Dates'),
            DB::raw('time as Time'),
            DB::raw('dish_name as Dish'),
            DB::raw("(CASE rotti WHEN 1 THEN 'Available' ELSE 'Unavailable' END) as Rotti_Available")
        )
        ->whereBetween('date', [$start_date_format, $end_date_format])
        ->where('tea' , NULL)
        ->get()
        ->toArray();
        return response(array(
            'meals' => $data,
        ));
    }

    /**
     *
     * Function to handle AJAX calls from view.tea.schedule JQuery DateRangePicker
     * @param string $start where start date is passed to the function
     * @param string @end where end date is passed down to the function
     * return response object
     *
    */

    public function dateRangerTea($start, $end){
        $time_1 = strtotime($start);
        $time_2 = strtotime($end);
        $start_date_format = date('Y-d-m' , $time_1);
        $end_date_format = date('Y-d-m' , $time_2);
        // $dates = $start_date_format .'-'. $end_date_format;
        $data = Meal_Schedule::select(
            DB::raw('date as Dates'),
            DB::raw('time as Time'),
            DB::raw('dish_name as Dish')
        )
        ->whereBetween('date', [$start_date_format, $end_date_format])
        ->where('rotti' , NULL)
        ->get()
        ->toArray();
        return response(array(
            'meals' => $data,
        ));
    }
}

resources/views/Admin/Employees/Add_Employee.blade.php
@extends('index')
@section('content')

<div class="box-body" style="background-color: white">
<form class="form" enctype="multipart/form-data" action="{{ route('employee.store') }}" method="POST" id="Add_user_form">
        @CSRF
        <div class="row" >
          <div class="col-md-6">
            <div class="form-group">
              <label for="fname">First Name</label>
              <input type="text" class="form-control{{ $errors->has('fname') ? ' is-invalid' : ''}}" name="fname" placeholder="John" id="fname" value="{{ old('fname') }}">
              @if ($errors->has('fname'))
                    <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('fname') }}</strong>
                    </span>
              @endif
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
                <label for="lname">Last Name</label>
                <input type="text" class="form-control{{ $errors->has('lname') ? ' is-invalid' : ''}}"  id="lname" name="lname" placeholder="Doe" value="{{ old('lname') }}">
                @if ($errors->has('lname'))
                <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('lname') }}</strong>
                </span>
                 @endif
            </div>
          </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <label for="mobile">Mobile</label>
                <input type="text" class="form-control{{ $errors->has('mobile') ? ' is-invalid' : ''}}" id="mobile" name="mobile" placeholder="03001234567" value="{{ old('mobile') }}">
                @if ($errors->has('mobile'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('mobile') }}</strong>
                </span>
                @endif
            </div>
            </div>
        <div class="col-sm-6">
                <label for="role">Role</label>
                <select class="form-control select2" style="width: 100%;" name="role" >
                    <option selected="selected" value=""> </option>
                    @if (Auth::user()->role == 'super_admin')
                    <option value="super_admin">Super Admin</option>
                    @endif
                    <option value="admin">Admin</option>
                    <option value="user">User</option>
                    <option value="cook">Cook</option>
                </select>
            </div>
        </div>
        <div class="row" style="margin-top:2%">
            <div class="col-sm-6">
                <div class="form-group">
                <label for="status">Status</label>
                <select name="status" id="status" class="form-control{{ $errors->has('status') ? 'is-invalid' : '' }}">
                <option value="active" selected>Active</option>
                <option value="inactive">In-Active</option>
                </select>
            </div>
            </div>
            <div class="col-sm-6">
            <div class="form-group">
                <label for="email">Email</label>
                    <input type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : ''}}" id="email" name="email" placeholder="Someone@example.com" value="{{ old('email') }}">
                    @if ($errors->has('email'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('email') }}</strong>
                    </span>
                    @endif
            </div>
        </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                     <label for="password">Password</label>
                     <input type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : ''}}" id="password" name="password" placeholder="********">
                    </div>
                </div>
            <div class="col-sm-6">
              <div class="form-group">
                <label for="con_pass">Confirm Password</label>
                <input type="password" class="form-control" name="con_pass" placeholder="********">
              </div>
            </div>
        </div>
        <div class="row" style="margin-top:2%">
          <div class="col-md-12">
            <button class="btn btn-success col-sm-3 pull-right" type="submit">Submit</button>
          </div>
        </div>
        </form>
    </div>
</div>


@push('css')
<!-- bootstrap datepicker -->
{{-- <link rel="stylesheet" href="{{ asset('css/bootstrap-datepicker.min.css') }}"> --}}
<!-- iCheck for checkboxes and radio inputs -->
{{-- <link rel="stylesheet" href="{{ asset('css/iCheck/all.css') }}"> --}}
<!-- Select2 -->
<link rel="stylesheet" href="{{ asset('css/select2.min.css') }}">
@endpush
@stop

@section('footer_scripts')
<script src="{{asset('js/select2.full.js')}}"></script>
<!-- InputMask -->
<script src="{{ asset('js/jquery.inputmask.js') }}"></script>
<script src="{{ asset('js/jquery.inputmask.date.extensions.js') }}"></script>
<script src="{{ asset('js/jquery.inputmask.extensions.js') }}"></script>
<!-- bootstrap datepicker -->
<script src="{{ asset('js/bootstrap-datepicker.min.js') }}"></script>
<!-- iCheck 1.0.1 -->
<script src="{{ asset('js/icheck.min.js') }}"></script>

@stop

resources/views/Admin/Employees/List_category.blade.php
@extends('index')
@section('content')
<div class="row">
    <div class="col-sm-12">
        <form action="" method="post">
            @csrf
        <div class="form-inline">
           <div class="col-sm-2">
                <label for="category">Category Name:</label>
           </div>
           <div class="col-sm-3">
                <input type="text" name="ctgry_name" placeholder="enter new category" class="form-control" width="100%" >
            </div>
            <div class="col-sm-3">
                <button type="submit" class="btn btn-success">Add New Category</button>
            </div>
        </div>
    </form>
    </div>
</div>
<div class="row" style="margin-top:3%">
    <div class="col-sm-12">
        <table class="table">
            <thead>
                <th>No.</th>
                <th>Category Name</th>
                <th>Num of Users</th>
                <th>Action</th>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@stop
@section('footer_scripts')
    <script>
    $(document).on('submit', 'form[data-confirm]', function(e){
    if(!confirm($(this).data('confirm'))){
    	e.stopImmediatePropagation();
      e.preventDefault();
		}
});
    </script>
@endsection

resources/views/Admin/Employees/List_employee.blade.php
@extends('index')
@section('content')
<div class="row">
    <div class="col-xs-4 ">
        <div class="input-group">
            <input type="text" class="form-control" onkeyup="search_name()" id="name"  placeholder="Jon Doe">
            <div class="input-group-btn search-panel">
                <button class="btn btn-success" style="border:none">
                    <span id="search_concept" style="color:white">Search By Name</span>
                </button>
            </div>
            <span class="input-group-btn">
                <i class="far fa-search"></i>
            </span>
        </div>
    </div>
        <div class="col-xs-4 ">
            <div class="input-group">
                <select id="role" class="form-control" onChange="search_role()">
                    <option value=""> </option>
                    <option value="super_admin">Super Admin</option>
                    <option value="admin">Admin</option>
                    <option value="user">User</option>
                    <option value="cook">Cook</option>
                    </select>
                <div class="input-group-btn search-panel">
                    <button class="btn btn-warning" style="border:none">
                        <span id="search_concept" style="color:white">Search By Role</span>
                    </button>
                </div>
                <span class="input-group-btn">
                    <i class="far fa-search"></i>
                </span>
        </div>
    </div>
        <div class="col-xs-4">
                <div class="input-group">
                    <input type="text" id="mobile" placeholder="search by mobile" class="form-control" onkeyup="search_mobile()">
                    <div class="input-group-btn search-panel">
                        <button class="btn btn-primary" style="border:none">
                            <span id="search_concept" style="color:white">Search By Mobile</span>
                        </button>
                    </div>
                    <span class="input-group-btn">
                        <i class="far fa-search"></i>
                    </span>
        </div>
    </div>

    </div>
{{-- <div class="row">
    <div class="col-sm-12">
        <div class="col-sm-4">
            <input type="text" id="name" placeholder="search by name" class="form-control" onkeyup="search_name()">
        </div>
        <div class="col-sm-4">
            <input type="text" id="mobile" placeholder="search by mobile" class="form-control" onkeyup="search_mobile()">
        </div>
        <div class="col-sm-4">
            <select id="role" class="form-control" onChange="search_role()">
            <option value=""> </option>
            <option value="super_admin">Super Admin</option>
            <option value="admin">Admin</option>
            <option value="user">User</option>
            <option value="cook">Cook</option>
            </select>
        </div>
    </div>
</div> --}}
{{-- <div class="row" style="margin-top:3%">
    <div class="col-sm-6">
    <a href="{{route('employee.create')}}">
    <button class="btn btn-success">+ Add New User</button>
    </a>
    </div>
</div> --}}
<div class="row" style="margin-top:4%">
    <div class="col-sm-12" style="background-color:white">
    <table class="table" id="myTable">
        <thead>
            <th>No.</th>
            <th>User Number</th>
            <th>Name</th>
            <th>Email</th>
            <th>Mobile</th>
            <th>Role</th>
            <th>Status</th>
            @if (Auth::user()->id == 'super_admin')
            <th>Actions</th>
            @endif
        </thead>
        <tbody>
            @foreach ($data as $info)
            <tr>
                <td class="counterCell"></td>
                <td>{{ $info->emp_num }}</td>
            <td>{{ $info->fname }} {{ $info->lname }}</td>
                <td>{{ $info->email }}</td>
                <td>{{ $info->mobile }}</td>
                <td>{{ $info->role }}</td>
                <td>{{ $info->status  }}</td>
                @if (Auth::user()->role == 'super_admin')
            <td><form action="{{ route('employee.destroy' , $info->id) }}" method="POST" data-confirm="Are you sure you want to delete this user?">
                    @CSRF @method('DELETE') <button type="submit" class="btn-xs btn-danger btn pull-left">Delete</button>
            </form><a href="{{ route('employee.edit',$info->id) }}" style="margin-left:1%"><button class="btn btn-xs btn-primary">Edit</button></a></td>
            </tr>
            @endif
            @endforeach
        </tbody>
    </table>
    {{ $data->links() }}
</div>
</div>
@stop
@section('footer_scripts')
<script>

function search_name() {
        var input, filter, table, tr, td, i;
        input = document.getElementById("name");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[2];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

    function search_mobile() {
        var input, filter, table, tr, td, i;
        input = document.getElementById("mobile");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[4];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

    function search_role() {
        var input, filter, table, tr, td, i;
        input = document.getElementById("role");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[5];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
    $(document).on('submit', 'form[data-confirm]', function(e){
    if(!confirm($(this).data('confirm'))){
    	e.stopImmediatePropagation();
      e.preventDefault();
		}
});
</script>
@endsection

resources/views/Admin/Employees/Profile.blade.php
@extends('index')
@section('content')
<div style="margin-bottom:4em">
<form class="form" id="Update_profile_form" action="{{ route('employee.update' , Auth::user()->id) }}" method="post" enctype="multipart/form-data">
        @CSRF
        @method('PATCH')
        <div class="form-group" style="margin-top:2%">
            <input type="file" name="img" class="form-control{{ $errors->has('img') ? ' is-invalid' : ''}}" id="imgInp" >
            @if($errors->has('img'))
                <span class="invalid-feedback">
                    <strong> {{ $errors->first('img')}}</strong>
                </span>
            @endif
        </div>
        <div class="form-group">
            <label for="password">New Password</label>
            <input type="password" name="password" id="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : ''}}" placeholder="Enter New Password">
            @if ($errors->has('password'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('password') }}</strong>
                </span>
            @endif
        </div>
        <div class="form-group" style="margin-bottom:4%">
            <label for="con_pass">Confirm Password</label>
            <input type="password" name="con_pass" id="con_pass" class="form-control{{ $errors->has('conpass') ? ' is-invalid' : ''}}" placeholder="Confirm Password">
            @if($errors->has('con_pass'))
                <span class="invalid-feedback">
                    <strong> {{$errors->first('con_pass')}}</strong>
                </span>
            @endif
        </div>
        <button type="submit" name="update_profile" value="update_profile" class="btn btn-primary form-control">Update Profile</button>
    </form>
</div>
<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#imgInp").change(function () {
        readURL(this);
    });

</script>
@stop
@section('section')
<h1> Update Profile </h1>
<hr>
<ol class="breadcrumb">
       <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
       <li class="active">Update Profile</li>
       </ol>
@endsection