routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login' ,' Auth\LoginController@showLoginForm')->name('login');
Route::post('/loggingin' , 'Auth\LoginController@attemptLogin')->name('loggingin');
route::post('/logout' , 'Auth\LoginController@logout')->name('logout');

// Extra Routes for web application to export Excel and PDF for meal schedule tea schedule and
// Inventory listing

Route::get('/meal/export', 'Admin\Employee\ExtraController@exportMeal')->name('export.meal');
Route::get('/export/meal' , 'Admin\Employee\ExtraController@exportExcel')->name('export.excel');
Route::get('/export/tea' , 'Admin\Employee\ExtraController@exportTea')->name('tea.pdf');
Route::get('tea/export', 'Admin\Employee\ExtraController@ExportTeaExcel')->name('export.tea.excel');
Route::get('date/{start}/{end}/fetch' , 'Admin\Employee\ExtraController@dateRanger');
Route::get('date/{start}/{end}/fetch/tea' , 'Admin\Employee\ExtraController@dateRangerTea');
Route::get('/export/inventory' , 'Admin\Employee\ExtraController@exportInventoryPDF')->name('inventory.pdf');
Route::get('/inventory/export' , 'Admin\Employee\ExtraController@exportInventoryExcel')->name('inventory.excel');
Auth::routes();

Route::middleware('auth')->group(function () {
Route::get('/', function () {
    return view('Admin.Dashboard');
})->name('admin.dashboard');

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where Admin Panel routes are registered. Navigation and operation
| against admin role is performed by these routes.
|
*/
Route::resource('employee', 'Admin\Employee\EmployeeController');
Route::resource('meal', 'Admin\Meals\MealController');
Route::resource('product', 'Admin\Products\ProductController');
Route::resource('productcat', 'Admin\Products\ProductcategoryController')->except(['create']);
Route::resource('inventory', 'Admin\Inventory\InventoryController');
Route::get('dish/view', ['as' => 'dish.index', 'uses' => 'Admin\Dish\DishController@index']);
Route::resource('tea', 'Admin\Meals\TeaController');
Route::resource('dish', 'Admin\Dish\DishController', ['names' => [
    'index' => 'dish.view'
]])->except([
    'index'
]);

});


/*
|--------------------------------------------------------------------------
| Cook Routes
|--------------------------------------------------------------------------
|
| Here is where Cook Panel routes are registered. Navigation and operation
| against cook role is performed by these routes.
|
*/





/*
|--------------------------------------------------------------------------
| System Handler Routes
|--------------------------------------------------------------------------
|
| Here is where Handler Panel routes are registered. Navigation and operation
| against handler role is performed by these routes.
|
*/

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'prd_name' , 'prd_ctgry' , 'prd_price', 'prd_qty', 'img'
    ];
}

app/Http/Controllers/Admin/Products/ProductController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use Illuminate\Http\Request;
use App\Http\Requests\Admin\AddProductRequest;
use App\Http\Controllers\Controller;
use App\Category;
use App\Product;
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Product::paginate(10);
        return view('Admin.products.View_products')->with(compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = Category::get()->toArray();
        return view('Admin.products.Add_product')->with(compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddProductRequest $request)
    {
        $data = $request->all();
        //checking if submit request has file
        if($request->hasFile('img')) {
            $file = $request->file('img');
            $filename = $file->getClientOriginalName();
            $extension = $file->getClientOriginalExtension();
            $imgname = uniqid().$filename;
            $destinationPath = public_path('/prd_img/');
            $file -> move($destinationPath , $imgname);
          }
          $product = Product::where('prd_name', '=', $data['prd_name'])->first();
            if ($product === null) {
                // user doesn't exist
          try {
              //if submit request has image
            if(!empty($data['img'])){
            $product = new Product();
            $product->prd_name = $data['prd_name'];
            $product->prd_ctgry = $data['prd_ctgry'];
            $product->prd_price = $data['prd_price'];
            $product->prd_qty = $data['prd_qty'];
            $product->img = $imgname;
            $product->save();
            }
            //if request is submitted without image
            else{
            $product = new Product();
            $product->prd_name = $data['prd_name'];
            $product->prd_ctgry = $data['prd_ctgry'];
            $product->prd_price = $data['prd_price'];
            $product->prd_qty = $data['prd_qty'];
            $product->save();
            }
         session()->flash('alert-success' , 'product has been added successfully');
         return redirect()->back();

        } catch (\Throwable $th) {
            session()->flash('alert-danger' , $th->getMessage());
            return redirect()->back();
          }
        }
        else{
            session()->flash('alert-danger' , 'Product Already Exists');
            return redirect()->back();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       return view('Admin.products.Transfer_products');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Product::findOrfail($id);
        $category = Category::select('category_name');
        // print_r($category);
       return view('Admin.products.Edit_product')->with(compact('data'))->with(compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        if($request->hasFile('img')) {
            $file = $request->file('img');
            $filename = $file->getClientOriginalName();
            $extension = $file->getClientOriginalExtension();
            $imgname = uniqid().$filename;
            $destinationPath = public_path('/prd_img/');
            $file -> move($destinationPath , $imgname);
          }
          try {
            if(!empty($data['img'])){
            Product::where('id', $id)->update(['prd_name'=>$data['prd_name'],
                                      'prd_ctgry'=>$data['prd_ctgry'],
                                      'prd_price' =>$data['prd_price'],
                                      'prd_qty' => $data['prd_qty'],
                                      'img'=> $imgname
            ]);
            }
            else{
                Product::where('id', $id)->update(['prd_name'=>$data['prd_name'],
                                      'prd_ctgry'=>$data['prd_ctgry'],
                                      'prd_qty' => $data['prd_qty'],
                                      'prd_price' =>$data['prd_price'],
                ]);
            }
         session()->flash('alert-success' , 'product has been updated successfully');
         return redirect()->route('product.index');

        } catch (\Throwable $th) {
            session()->flash('alert-danger' ,  $th->getMessage());
            return redirect()->back();
          }
        }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {

            Product::where('id', $id)->delete();
            session()->flash('alert-success' , 'product deleed successfully');
            return redirect()->back();

        } catch (\Throwable $th) {

            session()->flash('alert-danger', 'Product cannot be deleted, please try again');
            return redirect()->back();

        }
    }
}

app/Http/Controllers/Admin/Products/ProductcategoryController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use Illuminate\Http\Request;
use App\Http\Requests\Admin\AddProductcatRequest;
use App\Http\Controllers\Controller;
use App\Category;
use App\Product;
use DB;
class ProductcategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $data = Product::Join('categories' , 'products.prd_ctgry' , 'categories.category_name')->select(
            DB::raw('DISTINCT(products.prd_ctgry) as category'),
            DB::raw('COUNT(products.prd_name) as products'),
            DB::raw('categories.created_at as date')
        )->groupBy('products.prd_ctgry')->groupBy('categories.created_at')->get()->toArray();;

        return view('Admin.products.List_category')->with(compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddProductcatRequest $request)
    {
        try {

        Category::create($request->all());
        session()->flash('alert-success' , 'product category has been added successfully');
        return redirect()->back();

        } catch (\Throwable $th) {

            session()->flash('alert-danger', 'product category cannot be added, please try again');
            return redirect()->back();

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // echo $id;
        $ctgry_name = Category::where('category_name' , $id)->get();
        return response(array(
            'ctgry' => $ctgry_name
        ));

    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $id = $data['id'];

        try {

            Category::where('id', $id)->update([
                'category_name' => $data['category_name']
                ]);
            session()->flash('alert-success' , 'Category Updated Successfully');
            return redirect()->back();

        } catch (\Throwable $th) {

            session()->flash('alert-danger' , 'Cannot Update product category, please try again later');
            return redirect()->back();

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {

            Category::where('category_name', $id)->delete();
            session()->flash('alert-success' , 'Category has been deleted successfully');
            return redirect()->back();

        } catch (\Throwable $th) {

            session()->flash('alert-danger' , 'Category cannot be deleted, please try again');
            return redirect()->back();

        }
    }
}

resources/views/Admin/products/Add_product.blade.php
@extends('index')
@section('content')

<div class="row">
    <div class="col-sm-12" style="background-color:white">
    <form action="{{ route('product.store') }}" class="form" method="POST" enctype="multipart/form-data" id="Add_product_form">
        @CSRF
        <div class="row" style="margin-top:3%">
            <div class="form-group col-md-6">
                <label for="prd_name">Product Name</label>
            <input type="text" class="form-control{{ $errors->has('prd_name') ? 'is-invalid' : '' }}" name="prd_name" id="prd_name" placeholder="Enter Product Name" value="{{ old('prd_name') }}">
            @if ($errors->has('prd_name'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('prd_name') }}</strong>
                </span>
            @endif
            </div>
            <div class="form-group col-md-6">
                <label for="prd_ctgry">Product Category</label>
            <select name="prd_ctgry" id="prd_ctgry" class="form-control{{ $errors->has('prd_ctgry') ? 'is-invalid' : '' }}" value="{{ old('prd_ctgry') }}">
                    <option value=""></option>
                    @foreach($data as $info)
                <option value="{{ $info['category_name'] }}">{{ $info['category_name'] }}</option>
                    @endforeach
                </select>
                @if ($errors->has('prd_ctgry'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('prd_ctgry') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label for="">Price</label>
            <input type="text" class="form-control{{ $errors->has('prd_price') ? 'is-invalid' : '' }}" name="prd_price" id="prd_price" value="{{ old('prd_price') }}">
            @if ($errors->has('prd_price'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('prd_price') }}</strong>
                </span>
            @endif
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="prd_qty">Product Quantity</label>
            <input type="number" class="form-control{{ $errors->has('prd_qty') ? 'is-invalid' : ''}}" id="prd_qty" name="prd_qty">
            @if ($errors->has('prd_qty'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('prd_qty') }}</strong>
            </span>
            @endif
            </div>
        </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="img">Upload Image</label>
                    <input type="file" class="form-control{{ $errors->has('img') ? 'is-invalid' : '' }}" name="img" id="img">
                    @if ($errors->has('img'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('img') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
        </div>
        <div class="row" style="margin-top:2%">
            <div class="col-md-12">
                <button class="btn btn-success pull-right" type="submit" name="submit" value="submit">Submit</button>
            </div>
        </div>
        </form>
    </div>
    </div>

    @stop
    @section('footer_scripts')
        <script>
                $(document).ready(function(){
    $('input#prd_price').blur(function(){
        var num = parseFloat($(this).val());
        var cleanNum = num.toFixed(2);
        $(this).val(cleanNum);
        if(num/cleanNum < 1){
            $('#error').text('Please enter only 2 decimal places, we have truncated extra points');
            }
        });
    });
        </script>
    @endsection

resources/views/Admin/products/List_category.blade.php
@extends('index')
@section('content')
<div class="row">
    <div class="col-sm-12">
    <form action="{{ route('productcat.store') }}" method="post" id="Add_category_form">
            @csrf
        <div class="form-inline">
           <div class="col-sm-2">
                <label for="category">Category Name:</label>
           </div>
           <div class="col-sm-3">
           <input type="text" name="category_name" placeholder="enter new category" class="form-control{{ $errors->has('category_name') ? 'is-invalid' : '' }}" width="100%" value="{{ old('category_name') }}">
           @if ($errors->has('category_name'))
               <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->has('category_name') }}</strong>
               </span>
           @endif
            </div>
            <div class="col-sm-3">
                <button type="submit" class="btn btn-success">Add New Category</button>
            </div>
        </div>
    </form>
    </div>
</div>
<hr>
{{-- <div class="row">
        <div class="col-sm-12">
            <p style="padding:1%"><strong>Total Number of Categories</strong></p><hr>
            <table class="table table-bordered table-condensed">
                 <thead>
                    <th>No.</th>
                    <th>Category Name</th>
                    <th>Date Added</th>
                </thead>
                <tbody>
                    @foreach ($category as $info)
                    <tr>
                     <td class="counterCell"></td>
                     <td>{{ $info->category_name }}</td>
                     <td>{{ substr($info->created_at , 0, strrpos($info->created_at , ' ')) }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div> --}}
<div class="row" style="margin-top:3%">
    <div class="col-sm-12" style="background-color:white">
        <p style="padding:1%"><strong>Number of Products Added in Categories</strong></p><hr>
        <table class="table">
            <thead>
                <th>No.</th>
                <th>Category Name</th>
                <th>Num of Products</th>
                <th>Date</th>
                <th>Action</th>
            </thead>
            <tbody >
                @foreach ($data as $info)
                <tr>
                <td class="counterCell" ></td>
                <td>{{ $info['category'] }}</td>
                <td>{{ $info['products'] }} </td>
                <td>{{ substr($info['date'] , 0, strrpos($info['date'] , ' ')) }}</td>
                <td><form action="{{ route('productcat.destroy', $info['category']) }}" method="post" data-confirm="Are you sure you want to delete this category?">
                    @method('DELETE')
                    @CSRF
                    <button class="btn btn-danger btn-xs pull-left" type="submit">Delete</button>
                </form><button class="btn-primary btn btn-xs pull-left" value="{{ $info['category'] }}" id="edit">Edit</button></td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Edit Category</h4>
            </div>
            <div class="modal-body">
              <div class="row">
                <div class="col-sm-12">
                <form action="{{ route('productcat.update', $info['category']  ) }}" method="post">
                    @method('PUT')
                    @CSRF
                    <div class="form-group">
                        <label for="category_name">Category Name</label>
                        <div class="form-group">
                        <input type="hidden" value="" id="getid" name="id" class="in">
                            <input type="text" name="category_name" value="" class="form-control in" id="ctgry">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit" id="btn">Update</button>
                        </div>
                    </div>
                </form>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>
      </div>
@stop
@section('footer_scripts')
    <script>
    $(document).on('click', '#edit', function () {
            var url = "/productcat";
            var url2 = "/edit"
            var id = $(this).val();
            $.get(url + '/' + id + url2, function (data) {
               ctgry_name = data.ctgry[0].category_name
               id = data.ctgry[0].id
               var input = $("#ctgry")
               var input2 = $('#getid')
                    input.val(input.val() + ctgry_name)
                    input2.val(input2.val() + id)
               $("#myModal").modal("show")
            })
        });
    $('#MyModal').on('hidden.bs.modal', function () {
    $(this).find('form').trigger('reset');
})
$(document).on('submit', 'form[data-confirm]', function(e){
    if(!confirm($(this).data('confirm'))){
    	e.stopImmediatePropagation();
      e.preventDefault();
		}
});
    </script>
@endsection

resources/views/Admin/products/View_products.blade.php
@extends('index')
@section('content')
<div class="row">
    <div class="col-xs-4 ">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search by Name" onkeyup="s_name()" id="myInputname">
            <div class="input-group-btn search-panel">
                <button class="btn btn-success" style="border:none">
                    <span id="search_concept" style="color:white">Search By Name</span>
                </button>
            </div>
            <span class="input-group-btn">
                <i class="far fa-search"></i>
            </span>
        </div>
    </div>
        <div class="col-xs-4 ">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search by Category" onkeyup="category()" id="Input1">
                <div class="input-group-btn search-panel">
                    <button class="btn btn-warning" style="border:none">
                        <span id="search_concept" style="color:white">Search By Time</span>
                    </button>
                </div>
                <span class="input-group-btn">
                    <i class="far fa-search"></i>
                </span>
        </div>
    </div>
        <div class="col-xs-4">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search by Price" onkeyup="price()" id="Input2">
                    <div class="input-group-btn search-panel">
                        <button class="btn btn-primary" style="border:none">
                            <span id="search_concept" style="color:white">Search By price</span>
                        </button>
                    </div>
                    <span class="input-group-btn">
                        <i class="far fa-search"></i>
                    </span>
        </div>
    </div>

    </div>
    <div class="row" style="margin-top:4%">
        <div class="col-sm-12" style="background-color:white">
        <table class="table" id="myTable">
            <thead>
                <th>No.</th>
                <th>Name</th>
                <th>Category</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Date Added</th>
                <th>Product Image</th>
                <th>Actions</th>
            </thead>
            <tbody>
                @foreach($data as $info)
                <tr>
                    <td class="counterCell"></td>
                <td>{{ $info->prd_name }}</td>
                <td>{{ $info->prd_ctgry }}</td>
                <td>{{ $info->prd_price }}</td>
                <td>{{ $info->prd_qty }}</td>
                <td>{{ substr($info->created_at , 0, strrpos($info->created_at , ' ')) }}</td>
                <td><img src="{{ asset('/prd_img/'.$info->img) }}" alt="{{ $info->prd_name }}" width="50px" height="50px" class="modal-img" id="imageresource"></td>
                <td><form action="{{ route('product.destroy', $info->id) }}" method="post" data-confirm="Are you sure you want to delete this product?">
                    @method('DELETE')
                    @CSRF
                    <button class="btn btn-danger btn-xs pull-left" type="submit" >Delete</button>
                </form><a href="{{ route('product.edit', $info->id) }}" style="margin-left:3%"><button class="btn btn-primary btn-xs pull-left">Edit</button></a>
            <a href="{{ route('inventory.show',$info->id) }}"><button class="btn btn-default btn-xs pull-left">Inventory</button></a>
            </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {{ $data->links() }}
    </div>
    </div>
    @push('css')
    <style>
    img.modal-img {
        cursor: pointer;
        transition: 0.3s;
    }

    img.modal-img:hover {
        opacity: 0.7;
    }

    .img-modal {
        display: none;
        position: fixed;
        z-index: 99999;
        padding-top: 100px;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.9);
    }

    .img-modal img {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 200%;
    }

    .img-modal div {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 200px;
        text-align: center;
        color: #ccc;
        padding: 10px 0;
        height: 100px;
    }

    .img-modal img,
    .img-modal div {
        animation: zoom 0.6s;
    }

    .img-modal span {
        position: absolute;
        top: 15px;
        right: 35px;
        color: #f1f1f1;
        font-size: 40px;
        font-weight: bold;
        transition: 0.3s;
        cursor: pointer;
    }

    @media only screen and (max-width: 200px) {
        .img-modal img {
            width: 100%;
        }
    }

    @keyframes zoom {
        0% {
            transform: scale(0);
        }

        100% {
            transform: scale(1);
        }
    }

    .modal-full {
        min-width: 80%;
        margin-left: 19%;
    }

    .modal-full .modal-content {
        min-height: 100vh;
    }
    </style>
    @endpush
    @stop
    @section('footer_scripts')
        <script>
                $('img.modal-img').each(function () {
                var modal = $('<div class="img-modal"><span>&times;</span><img /><div></div></div>');
                modal.find('img').attr('src', $(this).attr('src'));
                if ($(this).attr('alt'))
                    modal.find('div').text($(this).attr('alt'));
                $(this).after(modal);
                modal = $(this).next();
                $(this).click(function (event) {
                    modal.show(300);
                    modal.find('span').show(0.3);
                });
                modal.find('span').click(function (event) {
                    modal.hide(300);
                });
            });
            $(document).keyup(function (event) {
                if (event.which == 27)
                    $('.img-modal>span').click();
            });

            function s_name() {
        var input, filter, table, tr, td, i;
        input = document.getElementById("myInputname");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[1];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

    function category() {
        var input, filter, table, tr, td, i;
        input = document.getElementById("Input1");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[2];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

    function price() {
        var input, filter, table, tr, td, i;
        input = document.getElementById("Input2");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[3];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

$(document).on('submit', 'form[data-confirm]', function(e){
    if(!confirm($(this).data('confirm'))){
    	e.stopImmediatePropagation();
      e.preventDefault();
		}
});

        </script>
    @endsection